import { Pokemon } from './class/pokemon';

export const POKEMONS: Pokemon[] = [
    {
        id: 1,
        name: 'Bulbasaur',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 2,
        name: 'Ivysaur',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 3,
        name: 'Venusaur',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 4,
        name: 'Charmander',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 5,
        name: 'Charmeleon',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 6,
        name: 'Charizard',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
        types: ['Fire', 'Flying'],
        created: new Date(),
    },
    {
        id: 7,
        name: 'Squirtle',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 8,
        name: 'Wartortle',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 9,
        name: 'Blastoise',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 10,
        name: 'Caterpie',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',
        types: ['Bug'],
        created: new Date(),
    },
    {
        id: 11,
        name: 'Metapod',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png',
        types: ['Bug'],
        created: new Date(),
    },
    {
        id: 12,
        name: 'Butterfree',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png',
        types: ['Bug', 'Flying'],
        created: new Date(),
    },
    {
        id: 13,
        name: 'Weedle',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png',
        types: ['Bug', 'Poison'],
        created: new Date(),
    },
    {
        id: 14,
        name: 'Kakuna',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png',
        types: ['Bug', 'Poison'],
        created: new Date(),
    },
    {
        id: 15,
        name: 'Beedrill',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png',
        types: ['Bug', 'Poison'],
        created: new Date(),
    },
    {
        id: 16,
        name: 'Pidgey',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    //up to pokemon 151
    { id: 17,
        name: 'Pidgeotto',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    {
        id: 18,
        name: 'Pidgeot',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    {
        id: 19,
        name: 'Rattata',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 20,
        name: 'Raticate',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 21,
        name: 'Spearow',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    {
        id: 22,
        name: 'Fearow',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    {
        id: 23,
        name: 'Ekans',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 24,
        name: 'Arbok',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 25,
        name: 'Pikachu',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png',
        types: ['Electric'],
        created: new Date(),
    },
    {
        id: 26,
        name: 'Raichu',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png',
        types: ['Electric'],
        created: new Date(),
    },
    {
        id: 27,
        name: 'Sandshrew',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png',
        types: ['Ground'],
        created: new Date(),
    },
    {
        id: 28,
        name: 'Sandslash',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png',
        types: ['Ground'],
        created: new Date(),
    },
    {
        id: 29,
        name: 'Nidoran',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 30,
        name: 'Nidorina',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png',
        types: ['Poison'],
        created: new Date(),
    },  
    {
        id: 31,
        name: 'Nidoqueen',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png',
        types: ['Poison', 'Ground'],
        created: new Date(),
    },
    {
        id: 32,
        name: 'Nidoran',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 33,
        name: 'Nidorino',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 34,
        name: 'Nidoking',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png',
        types: ['Poison', 'Ground'],
        created: new Date(),
    },
    {
        id: 35,
        name: 'Clefairy',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png',
        types: ['Fairy'],
        created: new Date(),

    },
    {
        id: 36,
        name: 'Clefable',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png',
        types: ['Fairy'],
        created: new Date(),
    },
    {
        id: 37,
        name: 'Vulpix',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 38,
        name: 'Ninetales',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 39,
        name: 'Jigglypuff',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png',
        types: ['Normal', 'Fairy'],
        created: new Date(),
    },
    {
        id: 40,
        name: 'Wigglytuff',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png',
        types: ['Normal', 'Fairy'],
        created: new Date(),
    },
    {
        id: 41,
        name: 'Zubat',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png',
        types: ['Poison', 'Flying'],
        created: new Date(),
    },
    {
        id: 42,
        name: 'Golbat',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png',
        types: ['Poison', 'Flying'],
        created: new Date(),
    },
    {
        id: 43,
        name: 'Oddish',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 44,
        name: 'Gloom',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 45,
        name: 'Vileplume',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 46,
        name: 'Paras',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png',
        types: ['Bug', 'Grass'],
        created: new Date(),
    },
    {
        id: 47,
        name: 'Parasect',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png',
        types: ['Bug', 'Grass'],
        created: new Date(),
    },
    {
        id: 48,
        name: 'Venonat',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png',
        types: ['Bug', 'Poison'],
        created: new Date(),
    },
    {
        id: 49,
        name: 'Venomoth',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png',
        types: ['Bug', 'Poison'],
        created: new Date(),
    },
    {
        id: 50,
        name: 'Diglett',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png',
        types: ['Ground'],
        created: new Date(),
    },
    {
        id: 51,
        name: 'Dugtrio',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png',
        types: ['Ground'],
        created: new Date(),
    },
    {
        id: 52,
        name: 'Meowth',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 53,
        name: 'Persian',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 54,
        name: 'Psyduck',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 55,
        name: 'Golduck',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 56,
        name: 'Mankey',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png',
        types: ['Fighting'],
        created: new Date(),
    },
    {
        id: 57,
        name: 'Primeape',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png',
        types: ['Fighting'],
        created: new Date(),
    },
    {
        id: 58,
        name: 'Growlithe',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 59,
        name: 'Arcanine',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 60,
        name: 'Poliwag',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 61,
        name: 'Poliwhirl',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 62,
        name: 'Poliwrath',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png',
        types: ['Water', 'Fighting'],
        created: new Date(),
    },
    {
        id: 63,
        name: 'Abra',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png',
        types: ['Psychic'],
        created: new Date(),
    },
    {
        id: 64,
        name: 'Kadabra',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png',
        types: ['Psychic'],
        created: new Date(),
    },
    {
        id: 65,
        name: 'Alakazam',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png',
        types: ['Psychic'],
        created: new Date(),
    },
    {
        id: 66,
        name: 'Machop',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png',
        types: ['Fighting'],
        created: new Date(),
    },
    {
        id: 67,
        name: 'Machoke',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png',
        types: ['Fighting'],
        created: new Date(),
    },
    {
        id: 68,
        name: 'Machamp',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png',
        types: ['Fighting'],
        created: new Date(),
    },
    {
        id: 69,
        name: 'Bellsprout',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 70,
        name: 'Weepinbell',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 71,
        name: 'Victreebel',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png',
        types: ['Grass', 'Poison'],
        created: new Date(),
    },
    {
        id: 72,
        name: 'Tentacool',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png',
        types: ['Water', 'Poison'],
        created: new Date(),
    },
    {
        id: 73,
        name: 'Tentacruel',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png',
        types: ['Water', 'Poison'],
        created: new Date(),
    },
    {
        id: 74,
        name: 'Geodude',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png',
        types: ['Rock', 'Ground'],
        created: new Date(),
    },
    {
        id: 75,
        name: 'Graveler',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png',
        types: ['Rock', 'Ground'],
        created: new Date(),
    },
    {
        id: 76,
        name: 'Golem',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png',
        types: ['Rock', 'Ground'],
        created: new Date(),
    },
    {
        id: 77,
        name: 'Ponyta',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 78,
        name: 'Rapidash',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 79,
        name: 'Slowpoke',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png',
        types: ['Water', 'Psychic'],
        created: new Date(),
    },
    {
        id: 80,
        name: 'Slowbro',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png',
        types: ['Water', 'Psychic'],
        created: new Date(),
    },
    {
        id: 81,
        name: 'Magnemite',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png',
        types: ['Electric', 'Steel'],
        created: new Date(),
    },
    {
        id: 82,
        name: 'Magneton',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png',
        types: ['Electric', 'Steel'],
        created: new Date(),
    },
    {
        id: 83,
        name: "Farfetch'd",
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    {
        id: 84,
        name: 'Doduo',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    {
        id: 85,
        name: 'Dodrio',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png',
        types: ['Normal', 'Flying'],
        created: new Date(),
    },
    {
        id: 86,
        name: 'Seel',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 87,
        name: 'Dewgong',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png',
        types: ['Water', 'Ice'],
        created: new Date(),
    },
    {
        id: 88,
        name: 'Grimer',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 89,
        name: 'Muk',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 90,
        name: 'Shellder',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png',
        types: ['Water'],
        created: new Date(),
    },
    {   
        id: 91,
        name: 'Cloyster',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png',
        types: ['Water', 'Ice'],
        created: new Date(),
    },
    {
        id: 92,
        name: 'Gastly',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png',
        types: ['Ghost', 'Poison'],
        created: new Date(),
    },
    {
        id: 93,
        name: 'Haunter',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png',
        types: ['Ghost', 'Poison'],
        created: new Date(),
    },
    {
        id: 94,
        name: 'Gengar',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png',
        types: ['Ghost', 'Poison'],
        created: new Date(),
    },
    {
        id: 95,
        name: 'Onix',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png',
        types: ['Rock', 'Ground'],
        created: new Date(),
    },
    {
        id: 96,
        name: 'Drowzee',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png',
        types: ['Psychic'],
        created: new Date(),
    },
    {
        id: 97,
        name: 'Hypno',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png',
        types: ['Psychic'],
        created: new Date(),
    },
    {
        id: 98,
        name: 'Krabby',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 99,
        name: 'Kingler',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 100,
        name: 'Voltorb',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png',
        types: ['Electric'],
        created: new Date(),
    },
    {
        id: 101,
        name: 'Electrode',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png',
        types: ['Electric'],
        created: new Date(),
    },
    {
        id: 102,
        name: 'Exeggcute',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png',
        types: ['Grass', 'Psychic'],
        created: new Date(),
    },
    {
        id: 103,
        name: 'Exeggutor',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png',
        types: ['Grass', 'Psychic'],
        created: new Date(),
    },
    {
        id: 104,
        name: 'Cubone',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png',
        types: ['Ground'],
        created: new Date(),
    },
    {
        id: 105,
        name: 'Marowak',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png',
        types: ['Ground'],
        created: new Date(),
    },
    {
        id: 106,
        name: 'Hitmonlee',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png',
        types: ['Fighting'],
        created: new Date(),
    },
    {
        id: 107,
        name: 'Hitmonchan',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png',
        types: ['Fighting'],
        created: new Date(),
    },
    {
        id: 108,
        name: 'Lickitung',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 109,
        name: 'Koffing',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 110,
        name: 'Weezing',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png',
        types: ['Poison'],
        created: new Date(),
    },
    {
        id: 111,
        name: 'Rhyhorn',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png',
        types: ['Ground', 'Rock'],
        created: new Date(),
    },
    {
        id: 112,
        name: 'Rhydon',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png',
        types: ['Ground', 'Rock'],
        created: new Date(),
    },  
    {
        id: 113,
        name: 'Chansey',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 114,
        name: 'Tangela',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png',
        types: ['Grass'],
        created: new Date(),
    },
    {
        id: 115,
        name: 'Kangaskhan',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 116,
        name: 'Horsea',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 117,
        name: 'Seadra',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 118,
        name: 'Goldeen',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 119,
        name: 'Seaking',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 120,
        name: 'Staryu',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 121,
        name: 'Starmie',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png',
        types: ['Water', 'Psychic'],
        created: new Date(),
    },
    {
        id: 122,
        name: 'Mr. Mime',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png',
        types: ['Psychic', 'Fairy'],
        created: new Date(),
    },
    {
        id: 123,
        name: 'Scyther',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png',
        types: ['Bug', 'Flying'],
        created: new Date(),
    },
    {
        id: 124,
        name: 'Jynx',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png',
        types: ['Ice', 'Psychic'],
        created: new Date(),
    },
    {
        id: 125,
        name: 'Electabuzz',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png',
        types: ['Electric'],
        created: new Date(),
    },
    {
        id: 126,
        name: 'Magmar',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 127,
        name: 'Pinsir',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png',
        types: ['Bug'],
        created: new Date(),
    },
    {
        id: 128,
        name: 'Tauros',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 129,
        name: 'Magikarp',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 130,
        name: 'Gyarados',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png',
        types: ['Water', 'Flying'],
        created: new Date(),
    },
    {
        id: 131,
        name: 'Lapras',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png',
        types: ['Water', 'Ice'],
        created: new Date(),
    },
    {
        id: 132,
        name: 'Ditto',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 133,
        name: 'Eevee',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 134,
        name: 'Vaporeon',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png',
        types: ['Water'],
        created: new Date(),
    },
    {
        id: 135,
        name: 'Jolteon',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png',
        types: ['Electric'],
        created: new Date(),
    },
    {
        id: 136,
        name: 'Flareon',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png',
        types: ['Fire'],
        created: new Date(),
    },
    {
        id: 137,
        name: 'Porygon',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 138,
        name: 'Omanyte',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png',
        types: ['Rock', 'Water'],
        created: new Date(),
    },
    {
        id: 139,
        name: 'Omastar',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png',
        types: ['Rock', 'Water'],
        created: new Date(),
    },
    {
        id: 140,
        name: 'Kabuto',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png',
        types: ['Rock', 'Water'],
        created: new Date(),
    },
    {
        id: 141,
        name: 'Kabutops',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png',
        types: ['Rock', 'Water'],
        created: new Date(),
    },
    {
        id: 142,
        name: 'Aerodactyl',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png',
        types: ['Rock', 'Flying'],
        created: new Date(),
    },
    {
        id: 143,
        name: 'Snorlax',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 144,
        name: 'Articuno',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png',
        types: ['Ice', 'Flying'],
        created: new Date(),
    },
    {
        id: 145,
        name: 'Zapdos',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png',
        types: ['Electric', 'Flying'],
        created: new Date(),
    },
    {
        id: 146,
        name: 'Moltres',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png',
        types: ['Fire', 'Flying'],
        created: new Date(),
    },
    {
        id: 147,
        name: 'Dratini',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png',
        types: ['Dragon'],
        created: new Date(),
    },
    {
        id: 148,
        name: 'Dragonair',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png',
        types: ['Dragon'],
        created: new Date(),
    },
    {
        id: 149,
        name: 'Dragonite',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png',
        types: ['Dragon', 'Flying'],
        created: new Date(),
    },
    {
        id: 150,
        name: 'Mewtwo',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png',
        types: ['Psychic'],
        created: new Date(),
    },
    {
        id: 151,
        name: 'Mew',
        hp: 25,
        cp: 5,
        picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png',
        types: ['Psychic'],
        created: new Date(),
    }
];
